# Generated by Django 4.2.9 on 2026-03-06 15:39

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'User',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CommunityEvent',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=150, null=True)),
                ('event_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Community_Event',
                'ordering': ['event_date'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('hospital_name', models.CharField(max_length=100)),
                ('added_by', models.ForeignKey(blank=True, db_column='added_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors_added', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Doctor',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(choices=[('ADMIN', 'Admin'), ('SENIOR', 'Senior'), ('CAREGIVER', 'Caregiver'), ('FAMILY', 'Family'), ('VOLUNTEER', 'Volunteer')], max_length=50, unique=True)),
            ],
            options={
                'db_table': 'Role',
            },
        ),
        migrations.CreateModel(
            name='CaregiverProfile',
            fields=[
                ('caregiver', models.OneToOneField(db_column='caregiver_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='caregiver_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('qualification', models.CharField(max_length=200)),
                ('experience_years', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Caregiver_Profile',
            },
        ),
        migrations.CreateModel(
            name='FamilyProfile',
            fields=[
                ('family', models.OneToOneField(db_column='family_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='family_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('relation', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Family_Profile',
            },
        ),
        migrations.CreateModel(
            name='SeniorProfile',
            fields=[
                ('senior', models.OneToOneField(db_column='senior_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='senior_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('age', models.IntegerField()),
                ('medical_history', models.TextField(blank=True, null=True)),
                ('emergency_contact', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Senior_Profile',
            },
        ),
        migrations.CreateModel(
            name='VolunteerProfile',
            fields=[
                ('volunteer', models.OneToOneField(db_column='volunteer_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='volunteer_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('skills', models.TextField(blank=True, null=True)),
                ('availability', models.CharField(blank=True, max_length=200, null=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Volunteer_Profile',
            },
        ),
        migrations.CreateModel(
            name='SOSRequest',
            fields=[
                ('sos_id', models.AutoField(primary_key=True, serialize=False)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('escalated_by', models.ForeignKey(blank=True, db_column='escalated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sos_escalated', to=settings.AUTH_USER_MODEL)),
                ('handled_by', models.ForeignKey(blank=True, db_column='handled_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sos_handled', to=settings.AUTH_USER_MODEL)),
                ('senior', models.ForeignKey(db_column='senior_id', on_delete=django.db.models.deletion.CASCADE, related_name='sos_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'SOS_Request',
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('reminder_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('reminder_type', models.CharField(choices=[('MEDICATION', 'Medication'), ('APPOINTMENT', 'Appointment'), ('DAILY_TASK', 'Daily Task')], default='DAILY_TASK', max_length=20)),
                ('reminder_time', models.DateTimeField()),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='reminders_created', to=settings.AUTH_USER_MODEL)),
                ('senior', models.ForeignKey(db_column='senior_id', on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Reminder',
                'ordering': ['reminder_time'],
            },
        ),
        migrations.CreateModel(
            name='HealthNote',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False)),
                ('note_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('senior', models.ForeignKey(db_column='senior_id', on_delete=django.db.models.deletion.CASCADE, related_name='health_notes', to=settings.AUTH_USER_MODEL)),
                ('written_by', models.ForeignKey(db_column='written_by', on_delete=django.db.models.deletion.CASCADE, related_name='health_notes_written', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Health_Note',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(db_column='receiver_id', on_delete=django.db.models.deletion.CASCADE, related_name='messages_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(db_column='sender_id', on_delete=django.db.models.deletion.CASCADE, related_name='messages_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Chat_Message',
                'ordering': ['sent_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('log_type', models.CharField(choices=[('CAREGIVER_ACTION', 'Caregiver Action'), ('VOLUNTEER_VISIT', 'Volunteer Visit')], max_length=20)),
                ('action', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(db_column='performed_by', on_delete=django.db.models.deletion.CASCADE, related_name='activities_performed', to=settings.AUTH_USER_MODEL)),
                ('senior', models.ForeignKey(db_column='senior_id', on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Activity_Log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.CASCADE, to='senior_buddy.role')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'User_Role',
                'unique_together': {('user', 'role')},
            },
        ),
        migrations.CreateModel(
            name='SeniorVolunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, db_column='assigned_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteer_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('senior', models.ForeignKey(db_column='senior_id', on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_assignments', to=settings.AUTH_USER_MODEL)),
                ('volunteer', models.ForeignKey(db_column='volunteer_id', on_delete=django.db.models.deletion.CASCADE, related_name='senior_volunteer_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Senior_Volunteer',
                'unique_together': {('senior', 'volunteer')},
            },
        ),
        migrations.CreateModel(
            name='SeniorFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(db_column='family_id', on_delete=django.db.models.deletion.CASCADE, related_name='senior_links', to=settings.AUTH_USER_MODEL)),
                ('senior', models.ForeignKey(db_column='senior_id', on_delete=django.db.models.deletion.CASCADE, related_name='family_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Senior_Family',
                'unique_together': {('senior', 'family')},
            },
        ),
        migrations.CreateModel(
            name='SeniorDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, db_column='added_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_mappings_added', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(db_column='doctor_id', on_delete=django.db.models.deletion.CASCADE, related_name='senior_assignments', to='senior_buddy.doctor')),
                ('senior', models.ForeignKey(db_column='senior_id', on_delete=django.db.models.deletion.CASCADE, related_name='doctor_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Senior_Doctor',
                'unique_together': {('senior', 'doctor')},
            },
        ),
        migrations.CreateModel(
            name='SeniorCaregiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('assigned_by', models.ForeignKey(blank=True, db_column='assigned_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caregiver_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('caregiver', models.ForeignKey(db_column='caregiver_id', on_delete=django.db.models.deletion.CASCADE, related_name='senior_assignments', to=settings.AUTH_USER_MODEL)),
                ('senior', models.ForeignKey(db_column='senior_id', on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Senior_Caregiver',
                'unique_together': {('senior', 'caregiver')},
            },
        ),
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REGISTERED', 'Registered'), ('ATTENDED', 'Attended'), ('CANCELLED', 'Cancelled')], default='REGISTERED', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='senior_buddy.communityevent')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='event_attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Event_Attendance',
                'unique_together': {('event', 'user')},
            },
        ),
    ]
