# Generated by Django 4.2.9 on 2026-03-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senior_buddy', '0003_user_fcm_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='log_type',
            field=models.CharField(choices=[('CAREGIVER_ACTION', 'Caregiver Action'), ('VOLUNTEER_VISIT', 'Volunteer Visit'), ('FAMILY_UPDATE', 'Family Update')], max_length=20),
        ),
    ]
