# Generated by Django 4.2.9 on 2026-03-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senior_buddy', '0004_alter_activitylog_log_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caregiverprofile',
            name='qualification',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='seniorprofile',
            name='emergency_contact',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
