# Generated by Django 4.2.9 on 2026-03-17 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import senior_buddy.models


class Migration(migrations.Migration):

    dependencies = [
        ('senior_buddy', '0005_alter_caregiverprofile_qualification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=senior_buddy.models.generate_code, max_length=6, unique=True)),
                ('for_role', models.CharField(choices=[('CAREGIVER', 'Caregiver'), ('VOLUNTEER', 'Volunteer')], max_length=20)),
                ('expires_at', models.DateTimeField(default=senior_buddy.models.default_expiry)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_codes_generated', to=settings.AUTH_USER_MODEL)),
                ('senior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invite_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Invite_Code',
            },
        ),
    ]
